### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test tap-oracle

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        # python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.7"]
    services:
      oracle:
        #image: container-registry.oracle.com/database/express:21.3.0-xe
        #image: container-registry.oracle.com/database/free:23.2.0.0
        # Docker Hub image (feel free to change the tag "latest" to any other available one)
        image: gvenzl/oracle-free:latest-faststart
        
        # Provide healthcheck script options for startup
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        env:
          ORACLE_PASSWORD: admin  # SYS, SYSTEM and PDBADMIN password
          APP_USER: my_user
          APP_USER_PASSWORD: password_i_should_change
        ports:
          - 1521:1521

    steps:
    - name: Get Oracle Sample Database Scripts
      uses: actions/checkout@master
      with:
        path: oracle-samples
        repository: oracle-samples/db-sample-schemas
        ref: v23.1
    - uses: actions/checkout@v3
      with:
        path: main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        cd ${GITHUB_WORKSPACE}/main
        pip install poetry
    - name: Install dependencies
      run: |
        cd ${GITHUB_WORKSPACE}/main
        poetry install
    - name: Create sample HR data
      run: |
        cd ${GITHUB_WORKSPACE}/main
        poetry run python tests/create_sample_data.py
      env:
        GITHUB_WORKSPACE: ${{ env.GITHUB_WORKSPACE }}
        TAP_ORACLE_HOST: localhost
        TAP_ORACLE_PORT: 1521
        TAP_ORACLE_USER: SYSTEM
        TAP_ORACLE_PASSWORD: admin
        TAP_ORACLE_SERVICE_NAME: FREEPDB1
    - name: Run pytest
      run: |
        cd ${GITHUB_WORKSPACE}/main
        poetry run tap-oracle --config=ENV --discover
      env:
        TAP_ORACLE_HOST: localhost
        TAP_ORACLE_PORT: 1521
        TAP_ORACLE_USER: my_user
        TAP_ORACLE_PASSWORD: password_i_should_change
        TAP_ORACLE_SERVICE_NAME: FREEPDB1
        TAP_ORACLE_FILTER_SCHEMAS: HR
