### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test tap-oracle

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        # python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.7"]
    services:
      oracle:
        #image: container-registry.oracle.com/database/express:21.3.0-xe
        image: container-registry.oracle.com/database/free:23.2.0.0
        env:
          ORACLE_PWD: admin  # SYS, SYSTEM and PDBADMIN password
        ports:
          - 1521:1521

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
      env:
        TAP_ORACLE_HOST: localhost
        TAP_ORACLE_PORT: 1521
        TAP_ORACLE_USER: scott
        TAP_ORACLE_PASSWORD: tiger
        TAP_ORACLE_SID: FREEPDB1
        TAP_ORACLE_ALIAS: SYSDBA
